export const START_LOADING = 'START_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';

export const SET_RECIPE = 'SET_RECIPE';
export const SET_FAVOUR_LIST = 'SET_FAVOUR_LIST';
export const SET_CUSTOM_DISH_TO_FAVOUR_LIST = 'SET_CUSTOM_DISH_TO_FAVOUR_LIST';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSED_MODAL = 'CLOSED_MODAL';
